### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by zhaozhiyi11** [shenyi0220/CP-Cluster#1]
请问适用于定向框吗？

**Comment by shenyi0220** [comment]
还没试过3D的框(topdown view)，不过我觉得应该也有效果，如果把IOU换成PIOU或者其他计算方法

**Comment by zhaozhiyi11** [comment]
> 还没试过3D的框(topdown view)，不过我觉得应该也有效果，可以尝试把IOU换成PIOU或者其他bbox相似度计算方法

好的谢谢
