### ISSUE TITLE
yolov5在coco-val数据集上测试

### ISSUE THREAD

**Issue by River-Cold** [shenyi0220/CP-Cluster#10]
![image](https://user-images.githubusercontent.com/80696033/195991837-0b505cb0-659d-4dea-bbcd-c3f4654bf2d1.png)
@shenyi0220 非常感谢您的工作，我在复现CP-cluster在yolov5上测试coco数据集的过程中发现yolov5自带计算出来的map@.5和pycocotools计算出来的AP50不一致，请问您在论文表中取的是上图红框中的哪一个呢？如果使用yolov5自带计算出来的map无法达到您论文中的精度，恳请您帮忙指导
![image](https://user-images.githubusercontent.com/80696033/195992401-d228b282-f062-4c5f-9b39-759fdba14e4f.png)

**Comment by shenyi0220** [comment]
Hi @River-Cold ,

Yolov5的模型版本更新很快，论文上的模型比较早，记得可能是v4还是v6早期版本，而最新的模型普遍应该比论文上的精确度高。我在Readme里的指标是6月初的v6版本，已经比论文里的模型精度要高了，最近不知道有没有又更新过。

**Comment by River-Cold** [comment]
> Hi @River-Cold ,
> 
> Yolov5的模型版本更新很快，论文上的模型比较早，记得可能是v4还是v6早期版本，而最新的模型普遍应该比论文上的精确度高。我在Readme里的指标是6月初的v6版本，已经比论文里的模型精度要高了，最近不知道有没有又更新过。

@shenyi0220 您好，我使用的是v6.1的模型版本，但在测试的时候发现mmcv库里soft_nms的AP50精度比torchvision.ops.nms的精度始终低一点，我在其他数据集上的测试结果也是降低甚至更差，在coco的测试结果记录如下：
![image](https://user-images.githubusercontent.com/80696033/196139036-a60f6f57-2828-4ea6-8f17-984a1ea5d162.png)
我的环境版本与您之前的版本也基本一致：torch1.10.1+python3.8.12+Cuda10.2，之前看到您讲的可能存在不适配的问题，我使用了您最新的仓库也没有解决这个问题，请问大佬是否有空帮忙在我的服务器上看一下我可能是哪里弄错了才造成不适配吗？恳请大佬指导

**Comment by shenyi0220** [comment]
额，用torchvision.NMS的时候你的iou不是应该设成0.65吗，才能达到最佳的mAP50-95。
通常iou设的越低，AP50越高，但平均mAP会下降。
CP在之前6月份的模型下yolov5s记得map50-95可以达到38.0, 原版的NMS是37.4

至于SoftNMS的表现我就管不了哈
