### ISSUE TITLE
在自己的代码上尝试

### ISSUE THREAD

**Issue by Autismab** [shenyi0220/CP-Cluster#11]
大佬您好，请问我没有用ultralytics的代码

# keep = nms(
                #     detections_class[:, :4],
                #     detections_class[:, 4] * detections_class[:, 5],
                #     nms_thres
                # )

dets , keep = soft_nms(detections_class[:, :4],
                    detections_class[:, 4] * detections_class[:, 5],
                    nms_thres,
                    sigma=0.5, min_score=0.001, method='linear', offset=0)
上面nms是torchvision，下面的是您的cp-cluster，请问这样更改就行了吗，而且我并没有用到dets这个参数。期待您的回复。

**Comment by Autismab** [comment]
跑了一晚上 效果不太好

**Comment by shenyi0220** [comment]
参考下这个？
https://github.com/shenyi0220/yolov5

cp成功编译了吗？

**Comment by Autismab** [comment]
编译成功了，上次有个地方没改，昨晚改好了跑了一下，AP50提了0.2个点，有办法再提点吗？谢谢作者大大！

**Comment by shenyi0220** [comment]
你只需要AP50?一般iou_threshold越大，AP50越高，但AP75会降低。

也可尝试如下方法
在nms.cpp中下面代码最后那个参数，试试看opt=1,2,3,4，默认是3

  return cp_cluster_impl(boxes, scores, dets, iou_threshold, min_score,
                         offset, 0.8f, 1, **3**);

**Comment by Autismab** [comment]
好的 谢谢了
