### ISSUE TITLE
mmcv安装问题

### ISSUE THREAD

**Issue by pipnc** [shenyi0220/CP-Cluster#4]
File "/yolov5-main/utils/general.py", line 31, in <module>
    from mmcv.ops import soft_nms, nms
  File "/yolov5-main/mmcv-main/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/yolov5-main/mmcv-main/mmcv/ops/active_rotated_filter.py", line 8, in <module>
    ext_module = ext_loader.load_ext(
  File "/yolov5-main/mmcv-main/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/anaconda3/envs/python/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /yolov5-main/mmcv-main/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z3nmsN2at6TensorES0_fi
大佬您好，我用的您的这个版本Yolov5:https://github.com/shenyi0220/yolov5以及mmcv: https://github.com/shenyi0220/mmcv，已经将mmcv/ops/csrc/pytorch/cpu/nms.cpp和mmcv/ops/csrc/pytorch/nms.cpp进行了替换，执行MMCV_WITH_OPS=1 pip install -e .安装mmcv提示成功安装1.4.4版本，但是运行val.py文件提示如上错误，我的pythorch版本是1.9.0，cuda11.1。

**Comment by shenyi0220** [comment]
额，这个，似乎是没找到mmcv，我在本地用的cuda10.2+pytorch1.8弄的，但我觉得可能是其他问题。
可以先尝试弄个标准的mmcv，能在yolov5里调用成功后，再上带cp-cluster的版本

**Comment by YangPeng61790312** [comment]
> File "/yolov5-main/utils/general.py", line 31, in from mmcv.ops import soft_nms, nms File "/yolov5-main/mmcv-main/mmcv/ops/**init**.py", line 2, in from .active_rotated_filter import active_rotated_filter File "/yolov5-main/mmcv-main/mmcv/ops/active_rotated_filter.py", line 8, in ext_module = ext_loader.load_ext( File "/yolov5-main/mmcv-main/mmcv/utils/ext_loader.py", line 13, in load_ext ext = importlib.import_module('mmcv.' + name) File "/anaconda3/envs/python/lib/python3.8/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) ImportError: /yolov5-main/mmcv-main/mmcv/_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z3nmsN2at6TensorES0_fi 大佬您好，我用的您的这个版本Yolov5:[https://github.com/shenyi0220/yolov5以及mmcv](https://github.com/shenyi0220/yolov5%E4%BB%A5%E5%8F%8Ammcv): [https://github.com/shenyi0220/mmcv，已经将mmcv/ops/csrc/pytorch/cpu/nms.cpp和mmcv/ops/csrc/pytorch/nms.cpp进行了替换，执行MMCV_WITH_OPS=1](https://github.com/shenyi0220/mmcv%EF%BC%8C%E5%B7%B2%E7%BB%8F%E5%B0%86mmcv/ops/csrc/pytorch/cpu/nms.cpp%E5%92%8Cmmcv/ops/csrc/pytorch/nms.cpp%E8%BF%9B%E8%A1%8C%E4%BA%86%E6%9B%BF%E6%8D%A2%EF%BC%8C%E6%89%A7%E8%A1%8CMMCV_WITH_OPS=1) pip install -e .安装mmcv提示成功安装1.4.4版本，但是运行val.py文件提示如上错误，我的pythorch版本是1.9.0，cuda11.1。
我也遇见了相同的问题，请问你解决了吗

**Comment by mastergao57** [comment]
一样的问题，有人解决吗？
