### ISSUE TITLE
Questions about how to use it for fasterrcnn which is based on detectron2.

### ISSUE THREAD

**Issue by Simon-Stma** [shenyi0220/CP-Cluster#9]
Your work is very constructive. I see that the framework you are using for fasterrcnn based on mmdetection, so how do I migrate the code to 101x-C4 backbone for fasterrcnn based on detectron2?

**Comment by shenyi0220** [comment]
Thanks a lot for interest in this work!!!
Unfortunately, there's no detectron2 based impl for the time being.
Welcome to contribute if you have interest. I'm still restricted to fully open source this work...
